spring:
  datasource:
    url: jdbc:postgresql://43.134.166.185:5432/scheduler
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Wasd2333
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: common
        credential:
          client-id: f3ee6226-fd8b-4cae-a9e7-f3c211b0970b
          client-secret:
        post-logout-redirect-uri: http://localhost:8080